name: Bump
description: checkout, checkout branch, create PR

inputs:
  token:
    description: git pat to execute git related commands
    required: true
  branch_name:
    description: Branch name for the PR
    required: true
  tag:
    description: New tag of the upstream library
    required: true
  sender:
    description: internal repo that trigger this event
    required: true
  setup-path:
    description: path of setup.py file
    required: true
    default: .
  test-mode:
    description: to test the workflow
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
    - name: Checkout branch
      shell: bash
      run: |
        # Git config
        git config user.name "GitHub Actions"
        git config user.email "scott.tiger@ominatechnologies.com"
        # Fetch latest
        git fetch -apq
        # Switch to the branch or create it
        git checkout -B ${{ inputs.branch_name }}
        git reset --hard origin/${{ inputs.branch_name }} || git push -u origin ${{ inputs.branch_name }}
        # Update setup.py with tag
        sed -i 's/^'"${{ inputs.sender }}"'_tag = .*$/'"${{ inputs.sender }}"'_tag = "${{ inputs.tag }}"/g' ${{ inputs.setup-path }}/setup.py
        # Add changelog entry
        sed -i "s/^++++$/++++\n- chore: Auto bump '"${{ inputs.sender }}"' to version ${{ inputs.tag }}/" CHANGELOG.rst
    - name: Create or Update Pull Request
      if: ${{ ! inputs.test-mode }}
      uses: gr2m/create-or-update-pull-request-action@v1.x
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        title: "Automatic bump of ${{ inputs.sender }} to version ${{ inputs.tag }}"
        body: |
          Update report
          - Bump ${{ inputs.sender }} to ${{ inputs.tag }}
          - Auto-generated by [create-pull-request](https://github.com/gr2m/create-or-update-pull-request-action)
        branch: ${{ inputs.branch_name }}
        path: "."
        commit-message: "chore: Auto bump ${{ inputs.sender }} to version ${{ inputs.tag }}"
        author: "GitHub Actions <scott.tiger@ominatechnologies.com>"
        auto-merge: squash
        update-pull-request-title-and-body: false
