name: Test PR
description: check if branch branch name exist in given list of repository

inputs:
  token:
    description: git pat to execute git related commands
    required: true
    default: ${{ github.token }}
  branch_name:
    description: branch name to check
    required: true
  upstreams:
    description: comma separated list of upstream to check
    required: true
  test-mode:
    description: to test the workflow
    required: false

runs:
  using: composite
  steps:
    - name: Check all upstream for branch name
      shell: bash
      run: |
        IFS=', ' read -r -a array <<< "${{ inputs.upstreams }}"
        state=0
        for element in "${array[@]}"
        do
          git ls-remote --exit-code https://${{ inputs.token }}@github.com/ominatechnologies/${element}.git --heads origin ${{ inputs.branch_name }} && state=$(($state==0 || 1)) || echo ''
        done
        exit $state
